### ISSUE TITLE
RustEmbed of UI fails

### ISSUE THREAD

**Issue by pm100** [trailbaseio/trailbase#10]
I assume I am missing a build step somewhere.

```
error: #[derive(RustEmbed)] folder '/home/pm100/work/trailbase/trailbase-core/../ui/auth/dist/' does not exist. cwd: '/home/pm100/work/trailbase'
   --> trailbase-core/src/auth/ui/mod.rs:260:1
    |
260 | / #[folder = "../ui/auth/dist/"]
```

All the RustEmbed folder directives refer to 'dist' directories which do not exist

**Comment by ignatz** [comment]
The build step exists: `trailbase-core/build.rs`. However, the build is probably failing for you. Maybe missing build dependencies such as pnpm?

As a leftover from early development, I had it so that debug builds wouldn't fail if there was an issue with the UI asset builds. I just changed this behavior to be less surprising, i.e. also debug builds with `cargo build` should now fail: https://github.com/trailbaseio/trailbase/commit/15fba9359e7799629599dc72b57a4733f548656e .

Hope that makes it clearer and sorry for the silent failure. Thanks for reaching out and if that doesn't fix your issue, please reopen. Thanks

**Comment by pm100** [comment]
@ignatz - could not reopen

**Comment by ignatz** [comment]
> @ignatz - could not reopen

TIL - apparently you cannot reopen your own issue because I own the project: https://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github :sigh: - apologies

**Comment by ignatz** [comment]
> this does not actually fix it. I now know that the issue is that I have no got pnpm installed but you do not report the failure in this case. Why? Because the missing binary is reported not as a bad error status on the Output object but as a Err return from output.

My bad, I only tested my change by breaking the JS builds. It should now be fixed by https://github.com/trailbaseio/trailbase/commit/54ea61788a356832caa9967ecb53e56c62075b10. I did remove `pnpm` from my PATH to make sure it triggers accordingly and added a more instructive error message.

I'll also keep the issue open in case you have more suggestions. Thanks

**Comment by ignatz** [comment]
I take your comment:

> if pnpm is missing then the build silently fails (fixed now - ty)

on https://github.com/trailbaseio/trailbase/discussions/13 as a signal to close this issue.
